name: AWS Authentication Reusable Workflow

on:
  workflow_call:
    inputs:
      corp-aws-access-key-id:
        description: "Corporate AWS Access Key ID"
        required: true
        type: string
      corp-aws-secret-access-key:
        description: "Corporate AWS Secret Access Key"
        required: true
        type: string
      corp-aws-region:
        description: "Corporate AWS Region"
        required: true
        type: string
      federal-aws-access-key-id:
        description: "Federal AWS Access Key ID"
        required: true
        type: string
      federal-aws-secret-access-key:
        description: "Federal AWS Secret Access Key"
        required: true
        type: string
      federal-aws-region:
        description: "Federal AWS Region"
        required: true
        type: string

jobs:
  setup-corp-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Corporate AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ inputs.corp-aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.corp-aws-secret-access-key }}
          aws-region: "us-east-1"

  setup-federal-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Federal AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ inputs.federal-aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.federal-aws-secret-access-key }}
          aws-region: "us-east-1"
