name: AuditBuddy CI

on:
    workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push framework service
      run: docker build -t framework_service:latest ./services/framework

    - name: Build and push providers service
      run: docker build -t providers_service:latest ./services/providers

    - name: Build and push utils service
      run: docker build -t utils_service:latest ./services/utils

    - name: Run Docker Compose
      run: docker-compose up --abort-on-container-exit