name: Run Okta Scripts

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-okta-scripts:
    runs-on: ubuntu-latest

    env:
      OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
      OKTA_API_TOKEN: ${{ secrets.OKTA_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: Run check-authentication-settings
        run: python src/evidence-collection/okta/check_authentication_settings.py

      - name: Run check-deactivated-users
        run: python src/evidence-collection/okta/check_deactivated_users.py

      - name: Run check-mfa-enrollments
        run: python src/evidence-collection/okta/check_mfa_enrollments.py

      - name: Run check-password-policies
        run: python src/evidence-collection/okta/check_password_policies.py

      - name: Run check-users-and-groups
        run: python src/evidence-collection/okta/check_users_and_groups.py
